project:
  type: website
  output-dir: docs

website:
  title: "Yazeed's Blog"
  navbar:
    left:
      - href: index.qmd
format:
  html:
    theme: lux
    toc: true
    smooth-scroll: true
    fig-align: center
