project:
  type: website

website:
  title: "Yazeed's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: super_blog.qmd
        text: My Story

format:
  html:
    theme: journal
    toc: true
    smooth-scroll: true
    fig-align: center
